services:
  postgres:
    container_name: inventory_dh
    image: postgres:latest

    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - 5432:5432

    volumes:
      - ./postgres:/var/lib/postgresql/data
